external_url 'http://192.168.1.2'
user['username'] = 'gitlab'
user['group'] = 'gitlab'
letsencrypt['enable'] = false
nginx['client_max_body_size'] = '250m'
# nginx['redirect_http_to_https'] = true
# nginx['ssl_certificate_key'] = '/etc/ssl/_ssc/auth.server.key'
# nginx['ssl_certificate'] = '/etc/ssl/_ssc/auth.server.crt'
gitlab_rails['gitlab_default_projects_features_builds'] = false
gitlab_rails['gitlab_default_projects_features_container_registry'] = false
gitlab_rails['omniauth_enabled'] = false
gitlab_rails['smtp_enable'] = false
gitlab_rails['smtp_pool'] = true
gitlab_rails['gitlab_email_from'] = 'gitlab@localhost'
gitlab_rails['gitlab_email_display_name'] = 'GitLab'
gitlab_rails['usage_ping_enabled'] = false
sidekiq['concurrency'] = 10
sidekiq['metrics_enabled'] = false
prometheus_monitoring['enable'] = false
puma['exporter_enabled'] = false
