global(
  PreserveFQDN="on"
  MaxMessageSize="16k"
  #LocalHostname="YourHostName"
)

module(
  Load="builtin:omfile"
  Template="RSYSLOG_SyslogProtocol23Format"
)

# action(
#   Type="omfwd"
#   KeepAlive="on"
#   KeepAlive.Probes="3"
#   KeepAlive.Interval="10"
#   KeepAlive.Time="60"
#   Target="192.168.1.2"
#   Port="514"
#   Protocol="tcp"
#   Queue.Type="linkedList"
# )
