# -------------------------------------------------------------------------------------------------------------------- #
# FTS: XAPIAN
# -------------------------------------------------------------------------------------------------------------------- #

fts_autoindex = yes

language "en" {
  default = yes
}

fts xapian {
  verbose = 0
  maxthreads = 2
  lowmemory = 300
  partial = 3
}

service indexer-worker {
  process_limit = 2
  vsz_limit = 512M
}
